### PR TITLE
Discord Embedded Notification

### PR DESCRIPTION
**Pull request by ibtvt**
Adds the ability to send webhook notifications to Discord with as embedded messages instead of raw text.  It looks prettier that way

image

I think I got it all right.  The startup notification works at least.

### CODE REVIEW

**Comment by ibtvt** [comment]
Added better formatting for download and delete notifications

image

**Comment by boredazfcuk** [comment]
Nice one. I'll merge this now, pull to my server, rebuild my containers, then check they work before rebuilding the images and pushing to Dockerhub,.. Shouldn't take long.

**Comment by ibtvt** [comment]
Shit.  Missed one bit.  

Need to add `&& [ -z "${discord_id}" ]` to the end of line 115

Otherwise you need to declare another notification type variable.

**Comment by boredazfcuk** [comment]
No worries. I'm just rebuilding a different container at the moment. Once it's done, I'll kick off another build of this one.

**Comment by boredazfcuk** [comment]
Sorted.

**Pull request merged**
