### PR TITLE
Align webhook messages with the other services

### PR DESCRIPTION
**Pull request by larstomas**
Just a suggestion. To make messages more similar on different services

### CODE REVIEW

**Comment by boredazfcuk** [comment]
Another good catch. Thanks for casting an eye over this. I get a bit code blind sometimes and it really helps having more than one set of eyes looking over things.

It also helps because I only use the Telegram notifications. The Webhook/Pushover/Pushbullet notification types were all requested so I never fully tested them. I just relied on the people that requested them to say they worked.

**Comment by larstomas** [comment]
Thank you, for putting this up in GitHub!

Had a hunch you were using Telegram. I tried with Pushbullet first, but it didn't work. After trying Pushover I was about to follow your example with Telegram.

**Comment by boredazfcuk** [comment]
Yeah I started out with Prowl, but they were very basic notifications. Someone requested Telegram so I installed to test. Ended up removing Prowl after that simply because I liked the emojis I can send. Other apps I have that use Telegram for notifications send images and web page previews which are nice too.

**Comment by larstomas** [comment]
Sounds nice 😊

I see that Pushbullet has an non working notification_url="https://pushbullet.weks.net/publicapi/add"
Looks very similar to Prowls notification_url="https://api.prowlapp.com/publicapi/add"

**Comment by boredazfcuk** [comment]
I spotted that too when I added Pushover notifications about a month ago.

It's because Pushbullet have released V2 of their API which has a different URL. I was going to update the script to use the new API so tried to download the app to test... but I found that they have actually pulled it from the App Store.

I was just going to remove Pushbullet notifications entirely. Not much point having it if they don't support iOS.

**Comment by larstomas** [comment]
👍 Agree, I would remove it.

**Comment by boredazfcuk** [comment]
Done

**Pull request merged**
