### PR TITLE
[update] 完善企业微信通知/Improve Wecom notification

### PR DESCRIPTION
**Pull request by Alano-i**
<div align=center></div>

### CODE REVIEW

**Comment by ershouqingge** [comment]
大佬跟进的好快。 之前咨询过你企业通知问题的，看来确实是项目太旧的问题，我以为是我配置问题

**Comment by boredazfcuk** [comment]
New container pushed to Dockerhub... v1.0.283 boredazfcuk/icloudpd:latest

**Comment by ershouqingge** [comment]
> boredazfcuk/icloudpd:latest

2023-04-12 09:51:00 WARINING WeCom notifications enabled, but configured incorrectly - disabling notifications


notification_type=WeCom
notification_title=icloudpd
name=jingzhe2
media_id_warning=2uWNJAcTK4dk2AAAAAAAAAAAAAAAAAAAAAAAAAAE0KqZqsirpBawZB4ESqMF
media_id_expiration=2uWNJAcTK4dAAAAAAAAAAAAAAAAAAAAAAAAAAE0KqZqsirpBawZB4ESqMF
media_id_download=2bo-Dhr724SIJAAAAAAAAAAAAAAAAAAAAAAAAAARI4ZVyFyckIu8oRFoxOW35Fw
media_id_startup=2FyUj63Ud83_UymAAAAAAAAAAAAAAAAAAAAAAAAAACsy8O4W46N1JSP
media_id_delete=2FVnQiSywzFXyXPtAAAAAAAAAAAAAAAAAAAAAAAAAAbUBoBkwUD0AavzkD08D
wecom_id=wwe4AAAAAA59d186e
wecom_secret=Jbo3TrWWxkNo0i0tAAAAAApgi5qR5VFXpB1VBQ
agentid=111111
touser=AAAAAA

**Comment by Alano-i** [comment]
日志发岀来看看

**Comment by ershouqingge** [comment]
> 日志发岀来看看

日志没有报错，只有一条通知配置错误警告的，你运行这个最新的docker通知正常吗？可否给个你的环境变量模板看下

2023-04-12 10:11:49 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****
2023-04-12 10:11:49 INFO     ***** https://github.com/boredazfcuk/docker-icloudpd *****
2023-04-12 10:11:49 INFO     ***** /usr/local/bin/sync-icloud.sh date: 2021/12/13_07:53 *****
2023-04-12 10:11:49 INFO     ***** /usr/local/bin/sync-icloud.sh hash: 74dfafa177492086fb3c777f518fbb55 *****
2023-04-12 10:11:49 INFO     Alpine Linux 3.13.5
2023-04-12 10:11:49 INFO     Python version: 3.8.10
2023-04-12 10:11:49 INFO     icloudpd version: 1.7.2
2023-04-12 10:11:51 INFO     pyicloud-ipd version: 0.10.1
2023-04-12 10:11:54 INFO     Running user id: 0
2023-04-12 10:11:54 INFO     Running group id: 0
2023-04-12 10:11:54 INFO     Local user: yan:1026
2023-04-12 10:11:54 INFO     Local group: users:100
2023-04-12 10:11:54 INFO     Force GID: False
2023-04-12 10:11:54 INFO     LAN IP Address: 172.17.0.8
2023-04-12 10:11:54 INFO     Default gateway: 172.17.0.1
2023-04-12 10:11:54 INFO     DNS server: 192.168.0.1
8.8.8.8
2023-04-12 10:11:54 INFO     DNS lookup for icloud.com.cn: 103.115.248.1
2023-04-12 10:12:16 INFO     Route check to icloud.com.cn successful
2023-04-12 10:12:16 INFO     Apple ID: AAAAAAAAA@qq.com
2023-04-12 10:12:16 INFO     Authentication Type: 2FA
2023-04-12 10:12:16 INFO     Cookie path: /config/AAAAAAAAAqqcom
2023-04-12 10:12:16 INFO     Cookie expiry notification period: 7
2023-04-12 10:12:16 INFO     Download destination directory: /iCloud
2023-04-12 10:12:16 INFO     Folder structure: {:%Y}
2023-04-12 10:12:16 INFO     Directory permissions: 775
2023-04-12 10:12:16 INFO     File permissions: 775
2023-04-12 10:12:16 INFO     Synchronisation interval: 43200
2023-04-12 10:12:16 INFO     Synchronisation delay (minutes): 0
2023-04-12 10:12:16 INFO     Time zone: Asia/Shanghai
2023-04-12 10:12:16 INFO     Set EXIF date/time: False
2023-04-12 10:12:16 INFO     Auto delete: True
2023-04-12 10:12:16 INFO     Photo size: original
2023-04-12 10:12:16 INFO     Skip download check: false
2023-04-12 10:12:16 INFO     Skip live photos: False
2023-04-12 10:12:16 INFO     Number of most recently added photos to download: Download All Photos
2023-04-12 10:12:16 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-04-12 10:12:16 INFO     Live photo size: original
2023-04-12 10:12:16 INFO     Skip videos: False
2023-04-12 10:12:16 INFO     Convert HEIC to JPEG: False
2023-04-12 10:12:16 INFO     JPEG conversion quality: 90
2023-04-12 10:12:16 INFO     Cleaned notification title: icloudpd
2023-04-12 10:12:16 WARINING WeCom notifications enabled, but configured incorrectly - disabling notifications
2023-04-12 10:12:16 INFO     Download notifications: Enabled
2023-04-12 10:12:16 INFO     Delete notifications: Enabled
2023-04-12 10:12:16 INFO     Downloading from: icloud.com.cn
2023-04-12 10:12:16 WARNING  Downloading from icloud.com.cn is untested. Please report issues at https://github.com/boredazfcuk/docker-icloudpd/issues
2023-04-12 10:12:19 INFO     Group, users:100, already created
2023-04-12 10:12:19 INFO     User, yan:1026, already created
2023-04-12 10:12:19 INFO     Set owner, yan, on iCloud directory, if required
2023-04-12 10:12:19 INFO     Set group, users, on iCloud directory, if required
2023-04-12 10:12:19 INFO     Correct owner on icloudpd temp directory, if required
2023-04-12 10:12:19 INFO     Correct group on icloudpd temp directory, if required
2023-04-12 10:12:19 INFO     Correct owner on config directory, if required
2023-04-12 10:12:19 INFO     Correct group on config directory, if required
2023-04-12 10:12:19 INFO     Correct owner on keyring directory, if required
2023-04-12 10:12:19 INFO     Correct group on keyring directory, if required
2023-04-12 10:12:19 INFO     Set 775 permissions on iCloud directories, if required
2023-04-12 10:12:19 INFO     Set 775 permissions on iCloud files, if required
2023-04-12 10:12:19 INFO     Configure password
2023-04-12 10:12:19 INFO     Using password stored in keyring file: /config/python_keyring/keyring_pass.cfg
2023-04-12 10:12:19 INFO     Check download directory mounted correctly
2023-04-12 10:12:19 INFO     Failsafe file /iCloud/.mounted exists, continuing.
2023-04-12 10:12:19 INFO     Set owner, yan, on iCloud directory, if required
2023-04-12 10:12:19 INFO     Set group, users, on iCloud directory, if required
2023-04-12 10:12:19 INFO     Correct owner on icloudpd temp directory, if required
2023-04-12 10:12:19 INFO     Correct group on icloudpd temp directory, if required
2023-04-12 10:12:19 INFO     Correct owner on config directory, if required
2023-04-12 10:12:19 INFO     Correct group on config directory, if required
2023-04-12 10:12:19 INFO     Correct owner on keyring directory, if required
2023-04-12 10:12:19 INFO     Correct group on keyring directory, if required
2023-04-12 10:12:19 INFO     Set 775 permissions on iCloud directories, if required
2023-04-12 10:12:20 INFO     Set 775 permissions on iCloud files, if required
2023-04-12 10:12:20 INFO     Sync user yan
2023-04-12 10:12:20 INFO     Synchronisation starting at 10:12:20
2023-04-12 10:12:20 INFO     Check 2FA Cookie
2023-04-12 10:12:20 INFO     Cookie exists, check expiry date
2023-04-12 10:12:20 INFO     Valid two factor authentication cookie found. Days until expiration: 88
2023-04-12 10:12:20 INFO     Check download directory mounted correctly
2023-04-12 10:12:20 INFO     Failsafe file /iCloud/.mounted exists, continuing.
ash: out of range
2023-04-12 10:12:20 INFO     Web cookie expires: 2023-06-10 @ 08:30:55
2023-04-12 10:12:20 INFO     Two factor authentication cookie expires: 2023-07-10 @ 08:31:10
2023-04-12 10:12:20 INFO     Days remaining until expiration: 88
2023-04-12 10:12:20 INFO     iCloud login counter = 0
2023-04-12 10:12:20 INFO     Synchronisation ended at 10:12:20
2023-04-12 10:12:20 INFO     Total time taken: 00:00:00
2023-04-12 10:12:20 INFO     Next synchronisation at 22:12:20

**Comment by Alano-i** [comment]
image

**Comment by ershouqingge** [comment]
> image

我配置的参数和你的是一样的 你现在用最新的这个可以正常通知吗

**Comment by Alano-i** [comment]
我用的是stable，通过-v映射出/usr/local/bin/sync-icloud.sh，把映射出来的文件改成最新的文件。

**Comment by ershouqingge** [comment]
> 我用的是stable，通过-v映射出/usr/local/bin/sync-icloud.sh，把映射出来的文件改成最新的文件。 image
> 
> 你检查一下icloudpd.conf这个文件里面的设置，看看是不是有缓存，环境变量设置的参数优先级低于这个配置文件，如果配置文件中有设置，即使修改了环境变量也不会生效

我看这问题里面也有这个错误 #16

**Comment by Alano-i** [comment]
不要删，直接在.config里面改配置，这个文件改了配置之后环境变量设置的就没用了

**Comment by ershouqingge** [comment]
> 不要删，直接在.config里面改配置，这个文件改了配置之后环境变量设置的就没用了

我在icloudpd.conf这个文件也添加了wecom通知的配置，还是一样的提示。

我觉得应该是sync-icloud.sh的问题，我用的也是stable，只有这个版本中国区可以获取cookie，无论是stable版本，还是通过stable获取stable后再升级latest版本，我这边都提示WeCom notifications enabled, but configured incorrectly - disabling notifications。

能能否给一份你的sync-icloud.sh文件呢，我尝试通过你的方法映射一下看

**Comment by ershouqingge** [comment]
> sync-icloud.sh就在这个仓库里啊。

image

不好意思 搞了半天有点懵了，我尝试了你的方法，使用stable版本，并且把latest版本的sync-icloud.sh映射到/usr/local/bin/sync-icloud.sh，结果还是一样的。

希望可以作者在latest版本中添加对中国icloud的支持和对wecom通知的适配 @boredazfcuk

**Comment by Alano-i** [comment]
I don't understand what you mean. You mean that you can notify normally by using the stable version and then mapping sync-icloud.sh?

Ps: The latest version does not need to map sync-icloud.sh. The latest version is already the latest sync-icloud.sh.

**Comment by ershouqingge** [comment]
> I don't understand what you mean. You mean that you can notify normally by using the stable version and then mapping sync-icloud.sh?
> 
> Ps: The latest version does not need to map sync-icloud.sh. The latest version is already the latest sync-icloud.sh.

We are users in China. The latest version cannot use China icloud, but stable can. Another user seems to be able to use the stable version and then map the latest version of the sh file to enable wecom notifications, but I have tried various methods but still can't work.

**Comment by Alano-i** [comment]
Can you show all your environment variable configurations and configurations in the .conf file?

In addition, are you sure that the wecom parameters you set are correct?

**Comment by ershouqingge** [comment]
> 



> Can you show all your environment variable configurations and configurations in the .conf file?
> 
> In addition, are you sure that the wecom parameters you set are correct?

I can be sure that the wecom I set up must be correct. First of all, I was configured in the environment variable. I found that the settings in the environment variable were not fully updated to the .conf file. Only some parameters were synchronized in the .conf file, but even if I complete the rest of the parameters into the .conf file, it was the same prompt for the lack of api/ Token

**Comment by Alano-i** [comment]
I use stable (mapping the latest sh file), everything is normal, including synchronizing icloud and wecom notifications.

**Comment by ershouqingge** [comment]
> show all your environment variable configurations and configurations in the .conf file?


Yes, only part of the configuration in the environment variable has been updated to the .conf file, but I can't complete the .conf. Could you please help me provide the content of your .conf file and environment variables? Please replace the privacy information in the middle part or therefore, please don't hide it completely. This will allow me to check again whether my variable parameter settings are correct.

**Comment by ershouqingge** [comment]
> Screenshot your .conf and environment variables. My configuration has been sent out,But you said that our configuration is the same, and I don't think it's possible.

感谢 已经配置好了，但是不知道为什么 ，使用你提交版本和最新版本的sh文件，文字部分乱码了。

使用stable原版文件不会。

image

**Pull request merged**
