### PR TITLE
Just a suggestion for notification titles.

### PR DESCRIPTION
**Pull request by waschinski**
I just think that "iCloud Photos Downloader" would make a better notification title than the repo name. Perfectly fine if you disagree on that but please fix that one white space in line 375 at least. :)

### CODE REVIEW

**Comment by waschinski** [comment]
Your implementation is even better, thanks for taking care of this so quickly!

**Comment by boredazfcuk** [comment]
Oops! 😂

I have two build scripts on my server. One builds locally and pushes to my private registry. My containers update from that and I test everything from there.

Once I’m happy with the changes, I update the readme and change.log and run a second build script which pushes code to GitHub and the image to DockerHub.

For some reason my local build has updated the code here before I’d finished testing. I’m out at minute so will have to sort this out properly when I get home later.

I did actually have the title as you suggested during my testing, but I found that it was too many characters so added a line break. I also wanted it to be distinctive from the container that the guys who run that iCloud_Photos_Downloader application. A few people using my container have registered issues on their Repo so sticking my name on it was to make a significant distinction between the two.

This way it will stay as default, so I still have that distinction, but people can set it to be whatever they like, coz it is a bit egotistical having my repo name on every notification lol

**Comment by waschinski** [comment]
haha, I actually didn't find it egoistical, more like a bit too technical. lol. Not that I don't know what I have set up but still. That extra white space was really bugging me though! :D

Anyway, looking forward to the new image on DockerHub. I've already set up the new env variable. Will see if the title I've set turns out to be too long.

Oh and thanks for all the work you put into this, of course!

**Comment by boredazfcuk** [comment]
I pushed this to Dockerhub an hour or two ago. It should all be good now. I've not done a huge amount of testing though. Re-created my container, saw the new startup message had the correct new title, changed it back and re-created again.

Stuff like the additional whitespace annoys me to. Thanks for the spot. If you find any more, just drop me another message.

**Pull request closed without merging**
