### PR TITLE
Please check change.log

### PR DESCRIPTION
**Pull request by bauzer714**
Recreated from #77 to resolve conflict.

@baccula  / @boredazfcuk  - Unless I'm missing something, the code in #74 doesn't work. Due to echo -e 2 backslashes is the same as a single backslash being passed to Notify, and the POST json string is still invalid. 

image

This is invalid:
image

The proper fix should have 5 backslashes.

image

image

image

### CODE REVIEW

**Comment by boredazfcuk** [comment]
Thanks

**Comment by boredazfcuk** [comment]
New images pushed to Dockerhub now

**Comment by bauzer714** [comment]
Great, pulled latest and it's working as expected.

image

**Comment by bauzer714** [comment]
@boredazfcuk  - Keep in mind that since $notification_title can take user value it's a bit fragile, but it's an edge case.

**Comment by boredazfcuk** [comment]
Yeah, I used to have it hard coded to boredazfcuk/icloudpd but somebody requested that it be a user editable field. Changed it to configurable as not many people would really want my internet name on every notification message.

I suppose I could always clean the string up with this bit of code:

```
notification_title="123@ ___MyTitle.\\\$%]"
notification_title="${notification_title//_/}"
notification_title="${notification_title// /_}"
notification_title="${notification_title//[^a-zA-Z0-9_]/}"
echo "${notification_title}"
```
It starts out with a string `123@ ___MyTitle.\\\$%` and turns it into `123_MyTitle`

Would that work? I'm not going to remove escape characters which may be deliberately passed in the `$notification_title` variable?

**Comment by bauzer714** [comment]
I wouldn't worry about it until an issue gets raised. Or mention in documentation that the notification title should not contain characters that might need special handling as JSON.

**Comment by boredazfcuk** [comment]
I've just added it anyway as I've pushed a new image with Alpine 3.14.

I've left spaces and underscore characters in as I guess hey should should be OK for a title. Just means a single line for the sanitisation:
```
notification_title="${notification_title//[^a-zA-Z0-9_ ]/}"
```
Plus an if statement so it kicks out a different log message.

**Pull request merged**
